FROM node:22-alpine
WORKDIR /app
RUN npm install -g pnpm@9
RUN corepack enable

ARG NEXT_PUBLIC_MAPBOX_TOKEN
ENV NEXT_PUBLIC_MAPBOX_TOKEN=$NEXT_PUBLIC_MAPBOX_TOKEN
ARG NEXT_PUBLIC_PUSHER_KEY
ENV NEXT_PUBLIC_PUSHER_KEY=$NEXT_PUBLIC_PUSHER_KEY
ARG NEXT_PUBLIC_PUSHER_CLUSTER
ENV NEXT_PUBLIC_PUSHER_CLUSTER=$NEXT_PUBLIC_PUSHER_CLUSTER
ARG NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm config set minimumReleaseAge 0
RUN pnpm install

COPY . .
RUN npx prisma generate
RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "start"]